**Ejercicio 11 **

Partiendo del DataFrame df mencionado anteriormente:

```
# Datos proporcionados
data = {
   'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
   'Edad': [25, 30, 22, 27],
   'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}
```

Realiza las siguientes operaciones:

1. Crea un dataframe llamado df

2. Agrega una nueva columna llamada Edad_en_10_años que contenga la edad de
las personas dentro de 10 años.

3. Modifica la columna Ciudad para que todas las ciudades estén en mayúsculas.

4. Crea una nueva columna Es_Mayor_de_25 que contenga valores booleanos: True
si la persona tiene 25 años o más, y False en caso contrario.