Ejercicio 2
Crea una serie de Pandas llamada:  serie_numeros   que contenga los números del 1 al 20. Luego, escribe un código que filtre y muestre solo aquellos números que sean mayores que 10. Utiliza una variable llamada filtro para almacenar la serie  filtrada.

In [15]:
import pandas as pd
from IPython.display import display, HTML

serie_numeros = pd.Series(range(1, 21))

serie_numeros_df = serie_numeros.reset_index()
serie_numeros_df.columns = ['Índice', 'Número']

#tabla original con estilo
print("Serie original:")
display(HTML(serie_numeros_df.style.set_table_attributes("style='display:inline'").set_caption("Números del 1 al 20").hide(axis='index').to_html()))

filtro = serie_numeros[serie_numeros > 10].reset_index()
filtro.columns = ['Índice', 'Número (>10)']

# tabla filtrada con estilo
print("\n Serie filtrada (mayores que 10):")
display(HTML(filtro.style.set_table_attributes("style='display:inline'").set_caption("Filtrados >10").hide(axis='index').to_html()))

Serie original:

 Serie filtrada (mayores que 10):