Ejercicio 9

Tu tabla de ventas, la columna "Precio" tiene algunos valores nulos.

```
data = {
   'ID': [1, 2, 3, 4],
   'Producto': ['Producto A', 'Producto B', 'Producto C', 'Producto D'],
   'Cantidad': [10, 20, 30, 40],
   'Precio': [100, None, 300, None]
}
```

Escribe un c√≥digo en Python usando Pandas para reemplazar los valores nulos en la columna Precio por el promedio de los precios no nulos de esa columna.

In [ ]:
import pandas as pd

data = {
   'ID': [1, 2, 3, 4, 5],
   'Producto': ['Producto A', 'Producto B', None, 'Producto D', 'Producto E'],
   'Cantidad': [10, 20, 30, None, 50],
   'Precio': [100, 200, 300, 400, None]
}

df = pd.DataFrame(data)

promedio_precio = df['Precio'].mean()

df['Precio'] = df['Precio'].fillna(promedio_precio)
print("\nDataFrame luego de reemplazar los nulos en 'Precio':")
print(df)

DataFrame luego de reemplazar los nulos en 'Precio':
   ID    Producto  Cantidad  Precio
0   1  Producto A      10.0   100.0
1   2  Producto B      20.0   200.0
2   3        None      30.0   300.0
3   4  Producto D       NaN   400.0
4   5  Producto E      50.0   250.0